import streamlit as st
import pandas as pd
from pptx import Presentation
from pptx.util import Inches, Pt
import io
from PIL import Image
import img2pdf
import time

# 1. Advanced App Setup
st.set_page_config(page_title="Cohelp AI | Virar", layout="wide", page_icon="🤝")

# 2. Sidebar Navigation
with st.sidebar:
    st.image("https://img.icons8.com/clouds/200/handshake.png")
    st.title("Cohelp AI")
    st.subheader("Business Suite")
    # This ensures the app starts on the Home Page
    menu = st.radio("Navigation", ["🏠 Home", "🪄 Prompt to PPT", "✉️ AI Email Pro", "📄 Photo to PDF", "📊 Data Analysis"])
    st.divider()
    st.caption("Founder: Harshid Bhatt | Virar, MH")

# --- 🏠 HOME PAGE (The first thing users see) ---
if menu == "🏠 Home":
    st.title("🤝 Welcome to Cohelp AI")
    st.subheader("The complete AI toolkit for Virar's entrepreneurs.")
    
    st.markdown("""
    Stop wasting hours on paperwork. Cohelp AI is designed to help you:
    * **Create Presentations** from a single thought.
    * **Draft Formal Emails** that sound professional.
    * **Convert Photos to PDF** for easy sharing.
    * **Analyze Sales Data** to grow your business.
    """)
    
    col1, col2 = st.columns(2)
    with col1:
        st.info("🚀 **Quick Tip:** Use the sidebar on the left to switch between different tools.")
    with col2:
        st.success("✅ **Status:** Your Pro Version is Active.")

# --- 🪄 PROMPT TO PPT (High Quality) ---
elif menu == "🪄 Prompt to PPT":
    st.header("🪄 AI Prompt to PPT")
    prompt = st.text_input("Enter your PPT Topic", placeholder="e.g. My 2024 Business Growth Plan")
    photos = st.file_uploader("Upload Images for Slides (Optional)", type=['jpg', 'png'], accept_multiple_files=True)
    
    if st.button("Generate Professional PPT"):
        if prompt:
            with st.spinner("Building your presentation..."):
                prs = Presentation()
                # Slide 1: Title
                slide = prs.slides.add_slide(prs.slide_layouts[0])
                slide.shapes.title.text = prompt.title()
                slide.placeholders[1].text = "Strategic Roadmap\nGenerated by Cohelp AI"

                # Slide 2: Strategic Points
                slide = prs.slides.add_slide(prs.slide_layouts[1])
                slide.shapes.title.text = "Key Objectives"
                tf = slide.shapes.placeholders[1].text_frame
                tf.text = f"Defining the vision for {prompt}"
                tf.add_paragraph().text = "• Market analysis and competitive positioning."
                tf.add_paragraph().text = "• Customer acquisition strategy for the local region."

                # Slide 3+: Pictures (If uploaded)
                if photos:
                    for p in photos:
                        slide = prs.slides.add_slide(prs.slide_layouts[1])
                        slide.shapes.title.text = "Supporting Visuals"
                        img = Image.open(p)
                        img_io = io.BytesIO()
                        img.save(img_io, format='PNG')
                        slide.shapes.add_picture(img_io, Inches(1.5), Inches(2), width=Inches(7))

                out = io.BytesIO()
                prs.save(out)
                st.download_button("📥 Download .pptx File", out.getvalue(), "Business_Presentation.pptx")
        else:
            st.warning("Please enter a topic first.")

# --- ✉️ AI EMAIL PRO (Realistic Templates) ---
elif menu == "✉️ AI Email Pro":
    st.header("✉️ Professional Email Writer")
    reason = st.text_area("What is the reason for this email?", placeholder="e.g. Asking a vendor for a discount...")
    
    if st.button("Generate Realistic Email"):
        if reason:
            # We use a professional structure here
            email_text = f"""
Subject: Formal Inquiry Regarding {reason[:40]}

Dear Sir/Madam,

I hope this email finds you well. I am reaching out to you on behalf of Cohelp AI.

Regarding {reason}, we would like to formally request your attention to this matter. We believe that addressing this promptly will allow both our businesses to maintain a high standard of operation and professional growth. 

Could you please provide your feedback or the necessary documentation by the end of the week? We value our collaboration and look forward to your positive response.

Best Regards,

Harshid Bhatt
Founder, Cohelp AI
Virar, Maharashtra
            """
            st.markdown("### ✉️ Final Professional Draft:")
            st.code(email_text, language="text")
            st.download_button("📥 Download Email as Document", email_text, "Professional_Email.txt")

# --- 📄 PHOTO TO PDF ---
elif menu == "📄 Photo to PDF":
    st.header("📄 Photo to PDF Scanner")
    scans = st.file_uploader("Upload Page Photos", type=['jpg', 'png'], accept_multiple_files=True)
    if st.button("Create PDF"):
        if scans:
            pdf = img2pdf.convert([s.getvalue() for s in scans])
            st.download_button("📥 Download Scanned PDF", pdf, "Cohelp_Scan.pdf")

# --- 📊 DATA ANALYSIS ---
elif menu == "📊 Data Analysis":
    st.header("📊 Business Data Intelligence")
    file = st.file_uploader("Upload Sales CSV/Excel", type=['csv', 'xlsx'])
    if file:
        df = pd.read_csv(file) if file.name.endswith('csv') else pd.read_excel(file)
        st.dataframe(df)
        st.write("### Data Visualization")
        st.area_chart(df.select_dtypes(include=['number']))
              
