import streamlit as st
import pandas as pd
from pptx import Presentation
from pptx.util import Inches, Pt
import io
from PIL import Image
import img2pdf
import time

# App Setup
st.set_page_config(page_title="Cohelp AI Pro", layout="wide")

# Sidebar
with st.sidebar:
    st.title("🤝 Cohelp AI")
    st.subheader("Virar Enterprise Suite")
    menu = st.radio("Select Professional Tool", 
                    ["Prompt to PPT (Full)", "AI Email Generator", "Photo to PDF Scanner", "Advanced Data Analysis"])

# --- 1. PROMPT TO PPT (The AI Architect) ---
if menu == "Prompt to PPT (Full)":
    st.header("🪄 AI Prompt to Presentation")
    st.write("Enter a topic or description, and I will generate a complete 5-slide PPT structure.")
    
    user_prompt = st.text_area("What should the PPT be about?", placeholder="e.g., A business plan for a new organic cafe in Virar West...")
    style = st.selectbox("Presentation Style", ["Corporate", "Creative", "Minimalist", "Educational"])
    
    if st.button("Generate Full PPT File"):
        if user_prompt:
            with st.spinner("AI is researching and designing your slides..."):
                time.sleep(2) # Simulating AI processing
                prs = Presentation()

                # Slide 1: Title
                slide1 = prs.slides.add_slide(prs.slide_layouts[0])
                slide1.shapes.title.text = user_prompt.title()
                slide1.placeholders[1].text = f"Strategy & Implementation Plan\nStyle: {style} | Generated by Cohelp AI"

                # Slide 2: Objectives (AI Generated logic)
                slide2 = prs.slides.add_slide(prs.slide_layouts[1])
                slide2.shapes.title.text = "Executive Summary & Goals"
                tf2 = slide2.shapes.placeholders[1].text_frame
                tf2.text = f"Key objectives for {user_prompt}:"
                tf2.add_paragraph().text = "• Market positioning and local competition analysis."
                tf2.add_paragraph().text = "• Identifying primary target audience and demographics."
                tf2.add_paragraph().text = "• Establishing core value propositions."

                # Slide 3: Strategy
                slide3 = prs.slides.add_slide(prs.slide_layouts[1])
                slide3.shapes.title.text = "Strategic Roadmap"
                tf3 = slide3.shapes.placeholders[1].text_frame
                tf3.text = "Phase 1: Initial setup and local branding."
                tf3.add_paragraph().text = "Phase 2: Digital outreach via WhatsApp and Social Media."
                tf3.add_paragraph().text = "Phase 3: Scaling operations and community engagement."

                # Slide 4: Budget & ROI
                slide4 = prs.slides.add_slide(prs.slide_layouts[1])
                slide4.shapes.title.text = "Financial Outlook"
                tf4 = slide4.shapes.placeholders[1].text_frame
                tf4.text = "Estimated Budget Allocation: Marketing (40%), Operations (40%), Tech (20%)."
                tf4.add_paragraph().text = "Projected ROI: Break-even within 6-8 months."

                # Slide 5: Conclusion
                slide5 = prs.slides.add_slide(prs.slide_layouts[1])
                slide5.shapes.title.text = "Next Steps & Contact"
                tf5 = slide5.shapes.placeholders[1].text_frame
                tf5.text = "Finalizing the vendor partnerships."
                tf5.add_paragraph().text = "Launching the first pilot program."
                tf5.add_paragraph().text = "\nContact: Harshid Bhatt | Cohelp AI"

                # Save to memory
                out = io.BytesIO()
                prs.save(out)
                
                st.success("✅ Your Full PPT is ready for download!")
                st.download_button("📥 Download .pptx File", out.getvalue(), "Cohelp_AI_Presentation.pptx")
        else:
            st.warning("Please enter a prompt first!")

# --- 2. AI EMAIL GENERATOR ---
elif menu == "AI Email Generator":
    st.header("✉️ Professional Email Writer")
    email_prompt = st.text_area("What is the reason for this email?", placeholder="e.g., Requesting a quote for 500kg of flour...")
    
    if st.button("Generate Full Email"):
        if email_prompt:
            draft = f"""
            Subject: Professional Inquiry: {email_prompt[:30]}...
            
            Dear Sir/Madam,
            
            I hope you are doing well. I am writing to you on behalf of Cohelp AI to discuss {email_prompt}.
            
            We are looking to move forward with this project quickly and professionally. Could you please provide the necessary details, pricing, or next steps so we can finalize our decision?
            
            Thank you for your assistance.
            
            Best Regards,
            
            Harshid Bhatt
            Founder, Cohelp AI
            """
            st.info("Here is your ready-to-use email:")
            st.write(draft)
            st.download_button("📥 Download as Text", draft, "Email_Draft.txt")

# --- 3. PHOTO TO PDF SCANNER ---
elif menu == "Photo to PDF Scanner":
    st.header("📄 Photo to PDF Scanner")
    files = st.file_uploader("Upload Document Photos", type=['jpg', 'png'], accept_multiple_files=True)
    if st.button("Create PDF"):
        if files:
            pdf_bytes = img2pdf.convert([f.getvalue() for f in files])
            st.download_button("📥 Download PDF", pdf_bytes, "Scanned_Document.pdf")

# --- 4. ADVANCED DATA ANALYSIS ---
elif menu == "Advanced Data Analysis":
    st.header("📊 Real Data Analysis")
    file = st.file_uploader("Upload Business Data", type=['csv', 'xlsx'])
    if file:
        df = pd.read_csv(file) if file.name.endswith('csv') else pd.read_excel(file)
        st.dataframe(df)
        st.write("### Quick Stats")
        st.write(df.describe())
        num_cols = df.select_dtypes(include=['number']).columns
        if not num_cols.empty:
            st.line_chart(df[num_cols[0]])
